### ISSUE TITLE
GA-03: Create IEEE Overleaf template document

### ISSUE THREAD

**Issue by TheCsarbeat** [TheCsarbeat/proyecto1-IA#4]
# Description

Create an overleaf document with IEEE template and invite collaborators. Define the general structure that will be followed based on the project specification.

# Acceptance Criteria

- **Paper structure:**
    - Define the general paper structure to be followed (Abstract, Introducción, Metodología, Resultados, Discusión y Conclusiones, Bibliografía.)
    - Fill out group and project important information, name, id, school etc...
- **Import necessary libraries:**
    - Use `listings` package to display code blocks and define **palette**
    - Rename listing default name for `Código`. Refer to [Latex How to change Listings name](https://latex.org/forum/viewtopic.php?t=25981)

**Comment by Chacalerks** [comment]
I created a project in LaTeX on the Overleaf Platform and have sent an invitation to each of your emails.

But I have questions about how the images and Python code should be structured. We should be able to add images on any page of the document, and I've created a section **Apéndices** for the Python code.

![image](https://github.com/TheCsarbeat/proyecto1-IA/assets/81202099/f7624cde-d9d4-47ea-aca7-7e1c9bdaa6ad)
---
### Note

- Save the files in the respective folder:
![image](https://github.com/TheCsarbeat/proyecto1-IA/assets/81202099/b4d49ac9-4862-4ba7-b423-beb3f2964ff3)

- For a Python code block, if you think it's not necessary to place it in a separate `.py` file, just add the code directly:
    - References to a file:
    
    ```latex
    \lstinputlisting[language=Python]{python_code/example_code.py}
    ```
   
   - Adding the code directly:
   
   ```latex
   \begin{lstlisting}[language=Python, caption=<the caption>]
     <code of python>
   \end{lstlisting}
   ```
